version: '3.7'
services:
  postgres-cadastro:
    container_name: postgres-cadastro-ifood
    image: postgres:12.2
    environment:
      POSTGRES_USER: cadastro
      POSTGRES_PASSWORD: cadastro
    ports:
      - "5432:5432"